const constants = {
  FETCH_PLACES: 'FETCH_PLACES',
  FETCH_PLACES_SUCCESS: 'FETCH_PLACES_SUCCESS',
  FETCH_PLACES_ERROR: 'FETCH_PLACES_ERROR',
  PLACE_ID: 'PLACE_ID',
  FETCH_PLACES_BEGIN: 'FETCH_PLACES_BEGIN',
  ADD_PLACE_SUCCESS: 'ADD_PLACE_SUCCESS',
  ADD_PLACE_FAILURE: 'ADD_PLACE_FAILURE',
  EDIT_PLACE: 'EDIT_PLACE',
  EDIT_PLACE_SUCCESS: 'EDIT_PLACE_SUCCESS',
  EDIT_PLACE_FAILURE: 'EDIT_PLACE_FAILURE',
  DELETE_PLACE: 'DELETE_PLACE',
  DELETE_PLACE_SUCCESS: 'DELETE_PLACE_SUCCESS',
  DELETE_PLACE_FAILURE: 'DELETE_PLACE_FAILURE',
  OPEN_MODAL: 'OPEN_MODAL',
  CLOSE_MODAL: 'CLOSE_MODAL',
  OPEN_SUPER_MODAL: 'OPEN_SUPER_MODAL',
  CLOSE_SUPER_MODAL: 'CLOSE_SUPER_MODAL',
};

export default constants;
